server:
  port: 3344

spring:
  application:
    name:  microservicespringcloudconfig
  cloud:
    config:
      server:
        git:
          uri: git@github.com:AK47Sonic/microservicespringcloudconfig.git #GitHub上面的git仓库名字


